name: fooddeliveryapp
description: "A new Flutter project."
# Ngăn chặn việc xuất bản gói vô tình lên pub.dev.
publish_to: 'none' 

# Định nghĩa phiên bản và build number cho ứng dụng.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Các thư viện phụ thuộc chính (Dependencies).
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^6.1.0 
  firebase_core: ^4.2.1 
  firebase_auth: ^6.1.2
  random_string: ^2.3.1 
  shared_preferences: ^2.2.2 
  http: ^1.1.0
  flutter_stripe: ^11.4.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  cloudinary_sdk: ^4.0.0
  flutter_map: ^6.1.0                     
  geolocator: ^10.1.0  
  geocoding: ^3.0.0
  latlong2: ^0.9.1     
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

# Các thư viện phục vụ quá trình phát triển (Dev Dependencies).
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # THÊM: Thư viện hỗ trợ tự động tạo App Icon.
  flutter_launcher_icons: ^0.13.1

# Cấu hình tự động tạo App Icon cho Android và iOS.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "D:/code/fooddeliveryapp1/fooddeliveryapp/images/logo_outside.png" # Đường dẫn tới file logo mới của bạn.
  adaptive_icon_background: "#ffffff" # Màu nền cho icon trên Android.
  adaptive_icon_foreground: "D:/code/fooddeliveryapp1/fooddeliveryapp/images/logo_outside.png"

# Cấu hình đặc thù cho Flutter.
flutter:
  # Đảm bảo các icon Material được bao gồm.
  uses-material-design: true

  # Khai báo các thư mục chứa tài nguyên (Assets).
  assets: # Khai báo đường dẫn đầy đủ tới thư mục chứa ảnh.
    - images/ 
    - assets/notification.mp3       # Giữ lại nếu bạn vẫn để ảnh ở thư mục images gốc.